project:
  type: website

website:
  title: "ML Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mrtunguyen
      - icon: twitter
        href: https://twitter.com/jonathan_ttu
format:
  html:
    theme: cosmo
    css: styles.css

comments:
  utterances:
    repo: https://github.com/mrtunguyen/mrtunguyen.github.io


