<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-02-16">
<meta name="description" content="Time Series Forecasting">

<title>ML Blog - Everything you need to know about Time Series Forecasting</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ML Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mrtunguyen" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/jonathan_ttu" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Everything you need to know about Time Series Forecasting</h1>
                  <div>
        <div class="description">
          Time Series Forecasting
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">time-series</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 16, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#time-series-definition" id="toc-time-series-definition" class="nav-link active" data-scroll-target="#time-series-definition">Time Series Definition</a>
  <ul class="collapse">
  <li><a href="#what-makes-time-series-forecasting-different-from-other-regression-tasks" id="toc-what-makes-time-series-forecasting-different-from-other-regression-tasks" class="nav-link" data-scroll-target="#what-makes-time-series-forecasting-different-from-other-regression-tasks">What makes time series forecasting different from other regression tasks?</a></li>
  </ul></li>
  <li><a href="#the-random-walk-process" id="toc-the-random-walk-process" class="nav-link" data-scroll-target="#the-random-walk-process">The random walk process</a>
  <ul class="collapse">
  <li><a href="#how-to-test-for-stionarity" id="toc-how-to-test-for-stionarity" class="nav-link" data-scroll-target="#how-to-test-for-stionarity">How to test for stionarity</a></li>
  <li><a href="#time-series-decomposition" id="toc-time-series-decomposition" class="nav-link" data-scroll-target="#time-series-decomposition">Time series decomposition</a></li>
  </ul></li>
  <li><a href="#statistical-models" id="toc-statistical-models" class="nav-link" data-scroll-target="#statistical-models">Statistical Models</a>
  <ul class="collapse">
  <li><a href="#moving-average" id="toc-moving-average" class="nav-link" data-scroll-target="#moving-average">Moving average</a></li>
  <li><a href="#autoregressive-process" id="toc-autoregressive-process" class="nav-link" data-scroll-target="#autoregressive-process">Autoregressive Process</a></li>
  <li><a href="#autoregressive-moving-average-arma-process" id="toc-autoregressive-moving-average-arma-process" class="nav-link" data-scroll-target="#autoregressive-moving-average-arma-process">Autoregressive Moving Average (ARMA) Process</a></li>
  <li><a href="#autoregressive-integrated-moving-average-arima-process" id="toc-autoregressive-integrated-moving-average-arima-process" class="nav-link" data-scroll-target="#autoregressive-integrated-moving-average-arima-process">Autoregressive Integrated Moving Average (ARIMA) Process</a></li>
  <li><a href="#seasonal-autoregressive-integrated-moving-average-sarima-process" id="toc-seasonal-autoregressive-integrated-moving-average-sarima-process" class="nav-link" data-scroll-target="#seasonal-autoregressive-integrated-moving-average-sarima-process">Seasonal Autoregressive Integrated Moving Average (SARIMA) Process</a></li>
  <li><a href="#sarima-with-external-variables-sarimax" id="toc-sarima-with-external-variables-sarimax" class="nav-link" data-scroll-target="#sarima-with-external-variables-sarimax">SARIMA with external variables (SARIMAX)</a></li>
  <li><a href="#vector-autoregression-var-model" id="toc-vector-autoregression-var-model" class="nav-link" data-scroll-target="#vector-autoregression-var-model">Vector AutoRegression (VAR) model</a></li>
  <li><a href="#prophet" id="toc-prophet" class="nav-link" data-scroll-target="#prophet">Prophet</a></li>
  </ul></li>
  <li><a href="#deep-learning" id="toc-deep-learning" class="nav-link" data-scroll-target="#deep-learning">Deep learning</a>
  <ul class="collapse">
  <li><a href="#multilayer-perceptron-mlp" id="toc-multilayer-perceptron-mlp" class="nav-link" data-scroll-target="#multilayer-perceptron-mlp">Multilayer Perceptron (MLP)</a></li>
  <li><a href="#recurrent-neural-network-rnn" id="toc-recurrent-neural-network-rnn" class="nav-link" data-scroll-target="#recurrent-neural-network-rnn">Recurrent Neural Network (RNN)</a></li>
  <li><a href="#convolutional-neural-network-cnn" id="toc-convolutional-neural-network-cnn" class="nav-link" data-scroll-target="#convolutional-neural-network-cnn">Convolutional Neural Network (CNN)</a></li>
  <li><a href="#temporal-convolutional-network-tcn" id="toc-temporal-convolutional-network-tcn" class="nav-link" data-scroll-target="#temporal-convolutional-network-tcn">Temporal Convolutional Network (TCN)</a></li>
  <li><a href="#transformer" id="toc-transformer" class="nav-link" data-scroll-target="#transformer">Transformer</a></li>
  <li><a href="#deepar" id="toc-deepar" class="nav-link" data-scroll-target="#deepar">DeepAR</a></li>
  </ul></li>
  <li><a href="#time-series-frameworks-and-libraries" id="toc-time-series-frameworks-and-libraries" class="nav-link" data-scroll-target="#time-series-frameworks-and-libraries">Time-series frameworks and libraries</a>
  <ul class="collapse">
  <li><a href="#prophet-1" id="toc-prophet-1" class="nav-link" data-scroll-target="#prophet-1">Prophet</a></li>
  <li><a href="#darts" id="toc-darts" class="nav-link" data-scroll-target="#darts">Darts</a></li>
  <li><a href="#neuralprophet" id="toc-neuralprophet" class="nav-link" data-scroll-target="#neuralprophet">NeuralProphet</a></li>
  <li><a href="#pytorch-forecasting" id="toc-pytorch-forecasting" class="nav-link" data-scroll-target="#pytorch-forecasting">pytorch-forecasting</a></li>
  </ul></li>
  <li><a href="#practical-example" id="toc-practical-example" class="nav-link" data-scroll-target="#practical-example">Practical example</a>
  <ul class="collapse">
  <li><a href="#dataset-overview" id="toc-dataset-overview" class="nav-link" data-scroll-target="#dataset-overview">Dataset overview</a></li>
  <li><a href="#identify-and-visualize-the-seasonal-component-of-the-time-series" id="toc-identify-and-visualize-the-seasonal-component-of-the-time-series" class="nav-link" data-scroll-target="#identify-and-visualize-the-seasonal-component-of-the-time-series">1. Identify and visualize the seasonal component of the time series</a></li>
  <li><a href="#apply-the-adf-test-to-check-if-the-time-series-is-stationary" id="toc-apply-the-adf-test-to-check-if-the-time-series-is-stationary" class="nav-link" data-scroll-target="#apply-the-adf-test-to-check-if-the-time-series-is-stationary">2. Apply the ADF test to check if the time series is stationary</a></li>
  <li><a href="#apply-a-transformation-to-make-the-time-series-stationary" id="toc-apply-a-transformation-to-make-the-time-series-stationary" class="nav-link" data-scroll-target="#apply-a-transformation-to-make-the-time-series-stationary">3. Apply a transformation to make the time series stationary</a></li>
  <li><a href="#fitting-arima-model" id="toc-fitting-arima-model" class="nav-link" data-scroll-target="#fitting-arima-model">Fitting ARIMA model</a></li>
  <li><a href="#fitting-sarima-model" id="toc-fitting-sarima-model" class="nav-link" data-scroll-target="#fitting-sarima-model">Fitting SARIMA model</a></li>
  <li><a href="#prophet-2" id="toc-prophet-2" class="nav-link" data-scroll-target="#prophet-2">Prophet</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">




<p>Time series exist in a variety of fields from meteorology to finance, econometrics, and marketing. By recording data and analyzing it, we can study time series to analyze industrial processes or track business metrics, such as sales or engagement. Also, with large amounts of data available, data scientists can apply their expertise to techniques for time series forecasting.</p>
<p>We will first learn how to make simple forecasts that will serve as benchmarks for more complex models. Then we will use two statistical learning techniques, the moving average model and the autoregressive model, to make forecasts. These will serve as the foundation for the more complex modeling techniques we will cover that will allow us to account for non-stationarity, seasonality effects, and the impact of exogenous variables. Afterwards, we’ll switch from statistical learning techniques to deep learning methods, in order to forecast very large time series with a high dimensionality, a sce- nario in which statistical learning often does not perform as well as its deep learning counterpart.</p>
<section id="time-series-definition" class="level2">
<h2 class="anchored" data-anchor-id="time-series-definition">Time Series Definition</h2>
<p>A time series is a set of data points ordered in time. The data is equally spaced in time, meaning that it was recorded at every hour, min- ute, month, or quarter. Typical examples of time series include the closing value of a stock, a household’s electricity consumption, or the temperature outside.</p>
<section id="what-makes-time-series-forecasting-different-from-other-regression-tasks" class="level3">
<h3 class="anchored" data-anchor-id="what-makes-time-series-forecasting-different-from-other-regression-tasks">What makes time series forecasting different from other regression tasks?</h3>
<ol type="1">
<li><strong>Temporal ordering</strong>: Time series have an order and the order of the observations matters. You can’t just treat the data as independent and identically distributed (i.i.d.) because the temporal ordering of the data matters.</li>
<li>Time series sometimes do not have features: With time series, it is quite common to be given a simple dataset with a time column and a value at that point in time. Without any other features, we must learn ways of using past values of the time series to forecast future values.</li>
<li>Speciality of time series forecasting:
<ul>
<li><strong>Seasonality</strong>: Many time series exhibit seasonality. For example, the number of airline passengers increases during the summer and decreases during the winter.</li>
<li><strong>Trends</strong>: Many time series exhibit trends. For example, the number of airline passengers has generally increased over time.</li>
<li><strong>Non-stationarity</strong>: Many time series are non-stationary. This means that the statistical properties of the time series, such as the mean or variance, change over time. For example, the number of airline passengers has generally increased over time, so the mean number of passengers is not constant.</li>
</ul></li>
</ol>
</section>
</section>
<section id="the-random-walk-process" class="level2">
<h2 class="anchored" data-anchor-id="the-random-walk-process">The random walk process</h2>
<p>A random walk is a process in which there is an equal chance of going up or down by a random number. Random walks often expose long periods where a positive or negative trend can be observed. They are also often accompanied by sudden changes in direction.</p>
<p>This is usually observed in financial and economic data, like the daily closing price of GOOGL.</p>
<p>In a random walk process, we say that the present value <span class="math inline">\(y_t\)</span> is a function of the value at the previous timestep <span class="math inline">\(y_{t –1}\)</span>, a constant C, and a random number <span class="math inline">\(ε_t\)</span> , also termed white noise. Here, <span class="math inline">\(ε_t\)</span> is the realization of the standard normal distribution, which has a variance of 1 and a mean of 0. Therefore, we can write the random walk process as:</p>
<p><span class="math display">\[y_t = C + y_{t-1} + ε_t\]</span></p>
<p>How to indentify a random walk process?</p>
<p>A random walk is a series whose first difference is stationary and uncorrelated. This means that the process moves completely at random.</p>
<blockquote class="blockquote">
<p>Stationarity:<br>
A stationary process is one whose statistical properties do not change over time. It means that it is said to be stationary if its mean, variance, and autocorrelation do not change over time.</p>
</blockquote>
<section id="how-to-test-for-stionarity" class="level3">
<h3 class="anchored" data-anchor-id="how-to-test-for-stionarity">How to test for stionarity</h3>
<p>💡 Augmented Dickey-Fuller (ADF) test</p>
<p>The augmented Dickey-Fuller (ADF) test helps us determine if a time series is stationary by testing for the presence of a unit root. If a unit root is present, the time series is not stationary.</p>
<p>The null hypothesis states that a unit root is present, meaning that our time series is not stationary.</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.stattools <span class="im">import</span> adfuller</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.graphics.tsaplots <span class="im">import</span> plot_acf</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>steps <span class="op">=</span> np.random.standard_normal(<span class="dv">1000</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>steps[<span class="dv">0</span>]<span class="op">=</span><span class="dv">0</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>random_walk <span class="op">=</span> np.cumsum(steps)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>ax.plot(random_walk)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Timesteps'</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Value'</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>ad_fuller_result <span class="op">=</span> adfuller(random_walk) <span class="co"># test for stationary</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'ADF Statistic: </span><span class="sc">{</span>ad_fuller_result[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'p-value: </span><span class="sc">{</span>ad_fuller_result[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF Statistic: -1.0137668210808588
p-value: 0.7482101114173918</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="time-series_files/figure-html/cell-2-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>The ADF statistic is not a large negative number, and with a p-value greater than 0.05, we cannot reject the null hypothesis stating that our time series is not stationary. We can further support our conclusion by plotting the ACF function.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>plot_acf(random_walk, lags<span class="op">=</span><span class="dv">20</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="time-series_files/figure-html/cell-3-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The autocorrelation coefficients slowly decrease as the lag increases, which is a clear indicator that our random walk is not a stationary process. The shaded area represents a confidence interval. If a point is within the shaded area, then it is not significantly different from 0. Otherwise, the autocor- relation coefficient is significant.</p>
<p>Because our random walk is not stationary, we need to apply a transformation to make it stationary in order to retrieve useful information from the ACF plot. Since our sequence mostly displays changes in the trend without seasonal patterns, we will apply a first-order differencing to our time series.</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>diff_random_walk <span class="op">=</span> np.diff(random_walk, n<span class="op">=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ADF_result <span class="op">=</span> adfuller(diff_random_walk)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'ADF Statistic: </span><span class="sc">{</span>ADF_result[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'p-value: </span><span class="sc">{</span>ADF_result[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF Statistic: -15.250889678624036
p-value: 5.01119615882467e-28</code></pre>
</div>
</div>
<p>This time the ADF statistic is a large negative number, and the p-value is less than 0.05. Therefore, we reject the null hypothesis, and we can say that this process has no unit root and is thus stationary.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>plot_acf(diff_random_walk, lags<span class="op">=</span><span class="dv">20</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="time-series_files/figure-html/cell-6-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>You’ll notice that there are no significant autocorrelation coefficients after lag 0. This means that the stationary process is completely random and can therefore be described as white noise. Each value is simply a random step away from the previous one, with no relation between them.</p>
</section>
<section id="time-series-decomposition" class="level3">
<h3 class="anchored" data-anchor-id="time-series-decomposition">Time series decomposition</h3>
<p><em>Time series decomposition</em> is a statistical task that separates the time series into its three main components: a trend component, a seasonal component, and the residuals.</p>
<ul>
<li>The trend component represents the long-term change in the time series. This component is responsible for time series that increase or decrease over time.</li>
<li>The seasonal component is the periodic pattern in the time series. It represents repeated fluctuations that occur over a fixed period of time.</li>
<li>Finally, the residuals, or the noise, express any irregularity that cannot be explained by the trend or the seasonal component.</li>
</ul>
<p>We will take a look at real world dataset. The Airline Passengers dataset describes the total number of airline passengers over a period of time. The units are a count of the number of airline passengers in thousands. There are 144 monthly observations from 1949 to 1960.</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.seasonal <span class="im">import</span> STL</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv'</span>, header<span class="op">=</span><span class="dv">0</span>, index_col<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>decomposition <span class="op">=</span> STL(df[<span class="st">'Passengers'</span>], period<span class="op">=</span><span class="dv">12</span>).fit()</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2, ax3, ax4) <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">4</span>, ncols<span class="op">=</span><span class="dv">1</span>, sharex<span class="op">=</span><span class="va">True</span>, figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">8</span>))</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>ax1.plot(decomposition.observed)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'Observed'</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>ax2.plot(decomposition.trend)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">'Trend'</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>ax3.plot(decomposition.seasonal)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>ax3.set_ylabel(<span class="st">'Seasonal'</span>)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>ax4.plot(decomposition.resid)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>ax4.set_ylabel(<span class="st">'Residuals'</span>)</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>plt.xticks(np.arange(<span class="dv">0</span>, <span class="dv">145</span>, <span class="dv">12</span>), np.arange(<span class="dv">1949</span>, <span class="dv">1962</span>, <span class="dv">1</span>))</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>fig.autofmt_xdate()</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="time-series_files/figure-html/cell-7-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="statistical-models" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="statistical-models">Statistical Models</h2>
<section id="moving-average" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="moving-average">Moving average</h3>
<p>A moving average process, or the moving average (MA) model, states that the current value is linearly dependent on the current and past error terms. The error terms are assumed to be mutually independent and normally distributed, just like white noise.</p>
<p>A moving average model is denoted as <span class="math inline">\(MA(q)\)</span>, where <span class="math inline">\(q\)</span> is the order. The model expresses the present value as a linear combination of the mean of the series <span class="math inline">\(\mu\)</span>, the present error term <span class="math inline">\(\epsilon_t\)</span>, and past error terms <span class="math inline">\(\epsilon_t - q\)</span>. The magnitude of the impact of past errors on the present value is quantified using a coefficient denoted as <span class="math inline">\(\theta_q\)</span>.</p>
<p><span class="math display">\[y_t = \mu + \epsilon_t + \theta_1 \epsilon_{t-1} + \theta_2 \epsilon_{t-2} + ... + \theta_q \epsilon_{t-q}\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="moving_average.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">moving average</figcaption>
</figure>
</div>
<aside>
<p>💡 <strong>Autocorrelation function</strong></p>
<p>The autocorrelation function (ACF) measures the linear relationship between lagged values of a time series.</p>
<p>In other words, it measures the correlation of the time series with itself.</p>
</aside>
</section>
<section id="autoregressive-process" class="level3">
<h3 class="anchored" data-anchor-id="autoregressive-process">Autoregressive Process</h3>
<p>An autoregressive process establishes that the output variable depends linearly on its own previous values. In other words, it is a regression of the variable against itself.</p>
<p>An autoregressive process is denoted as an <span class="math inline">\(AR(p)\)</span> process, where p is the order. In such a process, the present value <span class="math inline">\(y_t\)</span> is a linear combination of a constant <span class="math inline">\(C\)</span>, the present error term <span class="math inline">\(\epsilon_t\)</span>, which is also white noise, and the past values of the series <span class="math inline">\(y_t–p\)</span>. The magnitude of the influence of the past values on the present value is denoted as <span class="math inline">\(\phi_p\)</span>, which represents the coefficients of the <span class="math inline">\(AR(p)\)</span> model.</p>
<p><span class="math display">\[y_t = C + \phi_1 y_{t-1} + \phi_2 y_{t-2} + ... + \phi_p y_{t-p} + \epsilon_t\]</span></p>
<p>Similar to the moving average process, the order <span class="math inline">\(p\)</span> of an autoregressive process determines the number of past values that affect the present value</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="autoregressive.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Autoregressive step-by-step schema.</figcaption>
</figure>
</div>
</section>
<section id="autoregressive-moving-average-arma-process" class="level3">
<h3 class="anchored" data-anchor-id="autoregressive-moving-average-arma-process">Autoregressive Moving Average (ARMA) Process</h3>
<p>The autoregressive moving average process is a combination of the autoregressive process and the moving average process. It states that the present value is linearly dependent on its own previous values and a constant, just like in an autoregressive process, as well as on the mean of the series, the current error term, and past error terms, like in a moving average process.</p>
<p>The <span class="math inline">\(\text{ARMA(p, q)}\)</span> model consists of two types of lagged values, one for the autoregressive component and the other for the moving average component. The first parameter <span class="math inline">\(p\)</span> indicate the order of the autoregression, and the second <span class="math inline">\(q\)</span> the order of the moving average</p>
<p><span class="math display">\[y_t = C + \phi_1 y_{t-1} + \phi_2 y_{t-2} + ... + \phi_p y_{t-p} + \epsilon_t + \theta_1 \epsilon_{t-1} + \theta_2 \epsilon_{t-2} + ... + \theta_q \epsilon_{t-q}\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ARMA.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">ARMA steps-by-steps schema</figcaption>
</figure>
</div>
<p><strong>Understanding the Akaike information criterion (AIC)</strong></p>
<p>The AIC estimates the quality of a model relative to other models. Given that there will be some information lost when a model is fitted to the data, the AIC quantifies the relative amount of information lost by the model. The less information lost, the lower the AIC value and the better the model. The AIC is calculated as follows:</p>
<p><span class="math display">\[AIC = 2k - 2ln(\hat{L})\]</span></p>
<p>where k is the number of parameters in the model and <span class="math inline">\(\hat{L}\)</span> is the maximum value of the likelihood function for the model.</p>
<p><strong>Understanding residual analysis</strong></p>
<p>Residual analysis is a statistical technique used to assess the quality of a model. It is used to determine whether the assumptions of the model are valid and to identify any patterns in the residuals. The residuals are the differences between the observed values and the predicted values.</p>
<p>The residuals should be normally distributed, with a mean of 0 and a constant variance. If the residuals are not normally distributed, then the model is not capturing all the information in the data. If the residuals have a mean different from 0, then the model is biased. If the variance of the residuals is not constant, then the model is not capturing all the information in the data.</p>
<ul>
<li><p>The first step in residual analysis is to plot the quantile-quantile (Q-Q) plot of the residuals. The Q-Q plot is a graphical tool used to compare the distribution of the residuals to the normal distribution. If the residuals are normally distributed, the points in the Q-Q plot will fall on a straight line. If the residuals are not normally distributed, the points will deviate from the straight line.</p></li>
<li><p>The second step is to determinate if the residuals are uncorrelated. We will use the Ljung-Box test to determine if the residuals are uncorrelated. The null hypothesis of the Ljung-Box test is that the data is independently distributed, meaning that there is no autocorrelation. If the p-value of the Ljung-Box test is less than 0.05, then we reject the null hypothesis and conclude that the residuals are correlated.</p></li>
</ul>
</section>
<section id="autoregressive-integrated-moving-average-arima-process" class="level3">
<h3 class="anchored" data-anchor-id="autoregressive-integrated-moving-average-arima-process">Autoregressive Integrated Moving Average (ARIMA) Process</h3>
<p>So far, we have seen the autoregressive process, the moving average process, and the autoregressive moving average process. These models can only be applied to stationary time series, which required us to apply transformations, mainly differencing, and test for stationarity using the ADF test. The forecasts from each model returned differenced values, which we had to reverse to obtain the original values.</p>
<p>The autoregressive integrated moving average process, or ARIMA, is a generalization of the autoregressive moving average process that can be applied to non-stationary time series. Using this model, we can take into account non-stationary time series and avoid the steps of modeling on differenced data and having to inverse transform the forecasts.</p>
<p>The ARIMA model is denoted as ARIMA(p, d, q), where p is the order of the autoregressive component AR(p), d is the degree of differencing, and q is the order of the moving average component MA(q).</p>
<p><span class="math display">\[y'_t = C + \phi_1 y'_{t-1} + \phi_2 y'_{t-2} + ... + \phi_p y'_{t-p} + \epsilon_t + \theta_1 \epsilon'_{t-1} + \theta_2 \epsilon'_{t-2} + ... + \theta_q \epsilon'_{t-q}\]</span></p>
<p>where <span class="math inline">\(y'_t\)</span> is the differenced time series, and <span class="math inline">\(\epsilon'_t\)</span> is the differenced error term.</p>
<p>In simple terms, the ARIMA model is simply an ARMA model that can be applied on non-stationary time series.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ARIMA.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">ARIMA steps-by-steps schema</figcaption>
</figure>
</div>
</section>
<section id="seasonal-autoregressive-integrated-moving-average-sarima-process" class="level3">
<h3 class="anchored" data-anchor-id="seasonal-autoregressive-integrated-moving-average-sarima-process">Seasonal Autoregressive Integrated Moving Average (SARIMA) Process</h3>
<p><span class="math inline">\(\text{SARIMA(p,d,q)}(P,D,Q)_m\)</span> model expands on the ARIMA(p,d,q) model by adding seasonal parameters, where <em>P</em> is the order of the seasonal AR(<em>P</em>) process, <em>D</em> is the seasonal order of integration, <em>Q</em> is the order of the seasonal MA(<em>Q</em>) process, and <em>m</em> is the frequency, or the number of observations per seasonal cycle.</p>
<p>Note that a <span class="math inline">\(\text{SARIMA(p,d,q)}(0,0,0)_m\)</span> model is equivalent to an ARIMA(<em>p</em>,<em>d</em>,<em>q</em>) model.</p>
<p>The parameter m stands for the frequency, the number of observations per cycle. For data that was recorded every year, quarter, month, or week, the length of a cycle is considered to be 1 year. If the data was recorded annually, m = 1 since there is only one observation per year. If the data was recorded quarterly, m = 4 since there are four quarters in a year, and therefore four observations per year. Daily data can have a weekly seasonality. In that case, the frequency is m = 7 because there would be seven observations in a full cycle of 1 week. It could also have a yearly seasonality, meaning that m = 365. Thus, you can see that daily and sub-daily data can have a different cycle length, and therefore a different frequency m.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="SARIMA.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">SARIMA steps-by-steps schema</figcaption>
</figure>
</div>
</section>
<section id="sarima-with-external-variables-sarimax" class="level3">
<h3 class="anchored" data-anchor-id="sarima-with-external-variables-sarimax">SARIMA with external variables (SARIMAX)</h3>
<p>Each model that we have explored and used to produce forecasts has considered only the time series itself. In other words, past values of the time series were used as predictors of future values. However, it is possible that external variables also have an impact on our time series and can therefore be good predictors of future values.</p>
<p>The SARIMAX model simply adds a linear combination of exogenous variables to the SARIMA model. This allows us to model the impact of external variables on the future value of a time series.</p>
<p><span class="math display">\[x_t = \text{SARIMA(p, d, q) (P, D, Q)}_m + \sum_{i=1}^n \beta_i X_t^i\]</span></p>
<ul>
<li>Caveat using SARIMAX
<ul>
<li>Recall that the SARIMAX model uses the <span class="math inline">\(\text{SARIMA(p,d,q)}(P,D,Q)_m\)</span> **model and a linear combination of exogenous variables to predict one timestep into the future. But what if you wish to predict two timesteps into the future? While this is possible with a SARIMA model, the SARIMAX model requires us to forecast the exogenous variables too.</li>
<li>it can be forecast using a version of the SARIMA model. Nevertheless, we know that our forecast always has some error associated with it. Therefore, having to forecast an exogenous variable to forecast our target variable can magnify the prediction error of our target, meaning that our predictions can quickly degrade as we predict more timesteps into the future.</li>
</ul>
→ The only way to avoid that situation is to predict only one timestep into the future and wait to observe the exogenous variable before predicting the target for another timestep into the future.</li>
</ul>
</section>
<section id="vector-autoregression-var-model" class="level3">
<h3 class="anchored" data-anchor-id="vector-autoregression-var-model">Vector AutoRegression (VAR) model</h3>
<p>With the SARIMAX model, the relationship is unidirectional: we assume that the exogenous variable has an impact on the target only.</p>
<p>However, it is possible that two time series have a bidirectional relationship, meaning that time series t1 is a predictor of time series t2, and time series t2 is also a predictor for time series t1. In such a case, it would be useful to have a model that can take this bidirectional relationship into account and output predictions for <em>both</em> time series simultaneously.</p>
<p>→ Vector AutoRegression (VAR) allows us to capture the relationship between multiple time series as they change over time. That, in turn, allows us to produce forecasts for many time series simultaneously, therefore performing multivariate forecasting.</p>
<p>The VAR(<em>p</em>) model can be seen as a generalization of the AR(<em>p</em>) model that allows for multiple time series. Just like in the AR(<em>p</em>) model, the order <em>p</em> of the VAR(<em>p</em>) model determines how many lagged values impact the present value of a series. In this model, however, we also include lagged values of other time series.</p>
<p>For two time series, the general equation for the VAR(<em>p</em>) model is a linear combination of a vector of constants, past values of both time series, and a vector of error terms:</p>
<p><span class="math display">\[\begin{bmatrix} y_{1,t} \\ y_{2,t} \end{bmatrix} = \begin{bmatrix} C_1 \\ C_2 \end{bmatrix} + \begin{bmatrix} A^1_{11} &amp; A^1_{12} \\ A^1_{21} &amp; A^1_{22} \end{bmatrix} \begin{bmatrix} y_{1,t-1} \\ y_{2,t-1} \end{bmatrix} + \begin{bmatrix} A^2_{11} &amp; A^2_{12} \\ A^2_{21} &amp; A^2_{22} \end{bmatrix} \begin{bmatrix} y_{1,t-2} \\ y_{2,t-2} \end{bmatrix} + ... + \begin{bmatrix} \epsilon_{1,t} \\ \epsilon_{2,t} \end{bmatrix}\]</span></p>
<p>where <span class="math inline">\(y_{1,t}\)</span> and <span class="math inline">\(y_{2,t}\)</span> are the two time series, <span class="math inline">\(A_{ij}\)</span> are the coefficients of the autoregressive model, and <span class="math inline">\(\epsilon_{t}\)</span> is the error term.</p>
<p>Some importants points to take into account when using VAR model: - the time series must be stationary to apply the VAR model. - each time series has an impact on another. - it is important to test if whether past values of a time series are statistically significant in forecasting another time series -&gt; Granger causality test.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="VAR.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">VAR</figcaption>
</figure>
</div>
</section>
<section id="prophet" class="level3">
<h3 class="anchored" data-anchor-id="prophet">Prophet</h3>
<p>Prophet is a forecasting tool developed by Facebook. It is designed for forecasting time series data that display patterns on different time scales, such as yearly, weekly, and daily. It is based on an additive model where non-linear trends are fit with yearly, weekly, and daily seasonality, plus holiday effects. It works best with time series that have strong seasonal effects and several seasons of historical data. Prophet is robust to missing data and shifts in the trend, and typically handles outliers well.</p>
<p>Under the hood, Prophet implements a general additive model where each time series <span class="math inline">\(y(t)\)</span> is modeled as the linear combination of a trend <span class="math inline">\(g(t)\)</span>, a seasonal component <span class="math inline">\(s(t)\)</span>, holiday effects <span class="math inline">\(h(t)\)</span>, and an error term <span class="math inline">\(\epsilon_t\)</span>, which is normally distributed.</p>
<p><span class="math display">\[y(t) = g(t) + s(t) + h(t) + \epsilon_t\]</span></p>
<ul>
<li>The trend component models the non-periodic long-term changes in the time series.</li>
<li>The seasonal component models the periodic change, whether it is yearly, monthly, or weekly, or daily. The holiday effect occurs irregularly and potentially on more than one day. Finally, the error term represents any change in value that cannot be explained by the previous three components.</li>
</ul>
<p><strong>Seasonal periods</strong></p>
<p>The inclusion of multiple seasonal periods was motivated by the observation that human behavior produced multi-period seasonal time series. For example, the five day work week can produce a pattern that repeats every week, while school break can produce a pattern that repeats every year.</p>
<p>Thus, to take multiple seasonal periods into account, Prophet uses the Fourier series to model multiple periodic effects.</p>
<p><span class="math display">\[s(t) = \sum_{n=1}^N \Big( a_n cos(\frac{2\pi nt}{P}) + b_n sin(\frac{2\pi nt}{P}) \Big)\]</span></p>
<ul>
<li>N is simply the number of parameters we wish to use to estimate the seasonal component. The larger the value of N, the more complex the seasonal component will be.</li>
<li>if we have a yearly seasonality, P = 365.25, as there are 365.25 days in a year. For a weekly seasonality, P = 7</li>
</ul>
<p><strong>Holidays effect</strong></p>
<p>Holidays are irregular events that can have a clear impact on a time series.</p>
<ul>
<li>events such as Black Friday in the United States can dramatically increase the attendance in stores or the sales on an ecommerce website</li>
<li>Valentine’s Day is probably a strong indicator of an increase in sales of chocolates and flowers</li>
</ul>
<p>Prophet lets us define a list of holidays for a specific country. Holiday effects are then incorporated in the model, assuming that they are all independent. If a data point falls on a holiday date, a parameter <span class="math inline">\(K_i\)</span> is calculated to represent the change in the time series at that point in time. The larger the change, the greater the holiday effect.</p>
<p>If you want to deep dive into Prophet, check the official <a href="https://github.com/facebook/prophet">repo</a></p>
</section>
</section>
<section id="deep-learning" class="level2">
<h2 class="anchored" data-anchor-id="deep-learning">Deep learning</h2>
<blockquote class="blockquote">
<p>When to use deep learning for time series forecasting?</p>
</blockquote>
<p>Deep learning shines when we have large complex datasets (supposed to have more than 10K data points). In those situations, deep learning can leverage all the available data to infer relationships between each feature and the target, usually resulting in good forecasts.</p>
<ul>
<li>When we have a large enough dataset, a statistical model with take a long time to fit and forecast. In such a case, deep learning can be a good alternative.</li>
<li>When the dataset has a non-linear relationship between the features and the target, we should consider using deep learning.</li>
<li>When the data has multiple seasonal periods (hourly, daily, weekly, monthly, yearly), a SARIMAX model cannot be used. In such a case, deep learning should be considered.</li>
</ul>
<section id="multilayer-perceptron-mlp" class="level3">
<h3 class="anchored" data-anchor-id="multilayer-perceptron-mlp">Multilayer Perceptron (MLP)</h3>
<p>The most basic deep learning model is the multilayer perceptron (MLP). It is a feedforward neural network that consists of an input layer, one or more hidden layers, and an output layer. The input layer takes the features of the dataset, and the output layer returns the forecast. The hidden layers are responsible for learning the relationships between the features and the target.</p>
<p>In case of time series forecasting, the input layer takes the past values of the time series, and the output layer returns the forecast for the next value of the time series. The hidden layers are responsible for learning the relationships between the past values of the time series and the future value.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> compile_and_fit(model, window, patience<span class="op">=</span><span class="dv">3</span>, max_epochs<span class="op">=</span><span class="dv">50</span>):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    early_stopping <span class="op">=</span> EarlyStopping(monitor<span class="op">=</span><span class="st">'val_loss'</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                                   patience<span class="op">=</span>patience,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                                   mode<span class="op">=</span><span class="st">'min'</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">compile</span>(loss<span class="op">=</span>MeanSquaredError(),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                  optimizer<span class="op">=</span>Adam(),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                  metrics<span class="op">=</span>[MeanAbsoluteError()])</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    history <span class="op">=</span> model.fit(window.train,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>                       epochs<span class="op">=</span>max_epochs,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>                       validation_data<span class="op">=</span>window.val,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>                       callbacks<span class="op">=</span>[early_stopping])</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> history</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>dense <span class="op">=</span> Sequential([</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    Dense(units<span class="op">=</span><span class="dv">64</span>, activation<span class="op">=</span><span class="st">'relu'</span>),</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    Dense(units<span class="op">=</span><span class="dv">64</span>, activation<span class="op">=</span><span class="st">'relu'</span>),</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    Dense(units<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="co"># one step</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>history <span class="op">=</span> compile_and_fit(linear, single_step_window)</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>val_performance[<span class="st">'Linear'</span>] <span class="op">=</span> linear.evaluate(single_step_window.val)</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>performance[<span class="st">'Linear'</span>] <span class="op">=</span> linear.evaluate(single_step_window.test, verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a><span class="co"># multi step </span></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>history <span class="op">=</span> compile_and_fit(ms_dense, multi_window)</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>ms_val_performance[<span class="st">'Dense'</span>] <span class="op">=</span> ms_dense.evaluate(multi_window.val)</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>ms_performance[<span class="st">'Dense'</span>] <span class="op">=</span> ms_dense.evaluate(multi_window.test, verbose<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="recurrent-neural-network-rnn" class="level3">
<h3 class="anchored" data-anchor-id="recurrent-neural-network-rnn">Recurrent Neural Network (RNN)</h3>
<p>The recurrent neural network (RNN) is a type of neural network that is well-suited for time series forecasting. It is designed to take into account the sequential nature of time series data. The RNN has a feedback loop that allows information to be passed from one step of the network to the next. This feedback loop allows the RNN to take into account the past values of the time series when making a forecast.</p>
<p>The RNN is composed of a cell that takes the input and the hidden state from the previous timestep and returns the output and the hidden state for the current timestep. The hidden state is then passed to the next timestep, and so on. The output of the RNN is the forecast for the next value of the time series. There are many types of RNN cells, such as the simple RNN cell, the long short-term memory (LSTM) cell, and the gated recurrent unit (GRU) cell.</p>
<p>If you want to know more about LSTM, check this awsesome blog <a href="http://colah.github.io/posts/2015-08-Understanding-LSTMs/">Understanding LSTM Networks by Colah</a></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>lstm_model <span class="op">=</span> Sequential([</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    LSTM(<span class="dv">32</span>, return_sequences<span class="op">=</span><span class="va">False</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    Dense(units<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>history <span class="op">=</span> compile_and_fit(lstm_model, single_step_window)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="convolutional-neural-network-cnn" class="level3">
<h3 class="anchored" data-anchor-id="convolutional-neural-network-cnn">Convolutional Neural Network (CNN)</h3>
<p>A convolutional neural network is a deep learning architecture that makes use of convolutional operation. The convolution operation allows the network to create a reduced set of features. Therefore, it is a way of regularizing the network, preventing overfitting, and effectively filtering the inputs.</p>
<p>The convolution is performed with a kernel, which is also trained during model fitting. The stride of the kernel determines the number of steps it shifts at each step of the convolution. In time series forecasting, only <strong>1D convolution</strong> is used. To avoid reducing the feature space too quickly, we can use padding, which adds zeros before and after the input vector. This keeps the output dimension the same as the original feature vector, allowing us to stack more convolution layers, which in turn allows the network to process the features for a longer time.</p>
<blockquote class="blockquote">
<p>A 1D convolutional network takes as input a 3-dimensional tensor and also outputs a 3-dimensional tensor. The input tensor of our TCN implementation has the shape (batch_size, input_length, input_size) and the output tensor has the shape (batch_size, input_length, output_size). Since every layer in a TCN has the same input and output length, only the third dimension of the input and output tensors differs. In the univariate case, input_size and output_size will both be equal to one. In the more general multivariate case, input_size and output_size might differ since we might not want to forecast every component of the input sequence.<br>
One single 1D convolutional layer receives an input tensor of shape (batch_size, input_length, nr_input_channels) and outputs a tensor of shape (batch_size, input_length, nr_output_channels)</p>
</blockquote>
<div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>KERNEL_WIDTH <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>LABEL_WIDTH <span class="op">=</span> <span class="dv">24</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>INPUT_WIDTH <span class="op">=</span> LABEL_WIDTH <span class="op">+</span> KERNEL_WIDTH <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>cnn_model <span class="op">=</span> Sequential([</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    Conv1D(filters<span class="op">=</span><span class="dv">32</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>          kernel_size<span class="op">=</span>(KERNEL_WIDTH,),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>          activation<span class="op">=</span><span class="st">'relu'</span>),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    Dense(units<span class="op">=</span><span class="dv">32</span>, activation<span class="op">=</span><span class="st">'relu'</span>),</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    Dense(units<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>history <span class="op">=</span> compile_and_fit(cnn_model, conv_window)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="temporal-convolutional-network-tcn" class="level3">
<h3 class="anchored" data-anchor-id="temporal-convolutional-network-tcn">Temporal Convolutional Network (TCN)</h3>
<p>TCN consists of dilated, causal 1D convolutional layers with the same input and output lengths.</p>
<p>Advantages of TCN: - TCNs exhibit longer memory than recurrent architectures with the same capacity.<br>
- Performs better than LSTM/GRU on long time series (Seq. MNIST, Adding Problem, Copy Memory, Word-level PTB…).<br>
- Parallelism (convolutional layers), flexible receptive field size (how far the model can see), stable gradients (compared to backpropagation through time, vanishing gradients)…</p>
<p>A disadvantage of this basic design is that in order to achieve a long effective history size, we need an extremely deep network or very large filters.</p>
<p><strong>Dilated Casual convolutions</strong></p>
<p>The dilation part refers to the fact that points are skipped in the arrangement of the convolutional filters, such that any given point goes only into one convolutional filter in each level of layering. This promotes model sparsity and reduces redundant or overlapping convolutions, allowing the model to look further back in time while keeping overall computations reasonably contained.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tcn.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Dilated Casual Convolutions</figcaption>
</figure>
</div>
<div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> keras.layers <span class="im">import</span> Conv1D, Input, Add, Activation, Dropout</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> keras.models <span class="im">import</span> Sequential, Model</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> keras.layers.advanced_activations <span class="im">import</span> LeakyReLU, ELU</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> keras <span class="im">import</span> optimizers</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> tensorflow <span class="im">as</span> tf</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> DC_CNN_Block(nb_filter, filter_length, dilation):</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> f(input_):</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>        residual <span class="op">=</span>  input_</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>        layer_out <span class="op">=</span> Conv1D(</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>            filters<span class="op">=</span>nb_filter, kernel_size<span class="op">=</span>filter_length,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>            dilation_rate<span class="op">=</span>dilation,</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>            activation<span class="op">=</span><span class="st">'linear'</span>, padding<span class="op">=</span><span class="st">'causal'</span>, use_bias<span class="op">=</span><span class="va">False</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>            )(input_)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>        layer_out <span class="op">=</span> Activation(<span class="st">'selu'</span>)(layer_out)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>        skip_out <span class="op">=</span> Conv1D(<span class="dv">1</span>, <span class="dv">1</span>, activation<span class="op">=</span><span class="st">'linear'</span>, use_bias<span class="op">=</span><span class="va">False</span>)(layer_out)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>        network_in <span class="op">=</span> Conv1D(<span class="dv">1</span>, <span class="dv">1</span>, activation<span class="op">=</span><span class="st">'linear'</span>, use_bias<span class="op">=</span><span class="va">False</span>)(layer_out)</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>        network_out <span class="op">=</span> Add()([residual, network_in])</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> network_out, skip_out</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> f</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> DC_CNN_Model(length):</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>    <span class="bu">input</span> <span class="op">=</span> Input(shape<span class="op">=</span>(length,<span class="dv">1</span>))</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>    l1a, l1b <span class="op">=</span> DC_CNN_Block(<span class="dv">32</span>, <span class="dv">2</span>, <span class="dv">1</span>)(<span class="bu">input</span>)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>    l2a, l2b <span class="op">=</span> DC_CNN_Block(<span class="dv">32</span>, <span class="dv">2</span>, <span class="dv">2</span>)(l1a)</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>    l3a, l3b <span class="op">=</span> DC_CNN_Block(<span class="dv">32</span>, <span class="dv">2</span>, <span class="dv">4</span>)(l2a)</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>    l4a, l4b <span class="op">=</span> DC_CNN_Block(<span class="dv">32</span>, <span class="dv">2</span>, <span class="dv">8</span>)(l3a)</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>    l5a, l5b <span class="op">=</span> DC_CNN_Block(<span class="dv">32</span>, <span class="dv">2</span>, <span class="dv">16</span>)(l4a)</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>    l6a, l6b <span class="op">=</span> DC_CNN_Block(<span class="dv">32</span>, <span class="dv">2</span>, <span class="dv">32</span>)(l5a)</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>    l6b <span class="op">=</span> Dropout(<span class="fl">0.8</span>)(l6b)</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>    l7a, l7b <span class="op">=</span> DC_CNN_Block(<span class="dv">32</span>, <span class="dv">2</span>, <span class="dv">64</span>)(l6a)</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>    l7b <span class="op">=</span> Dropout(<span class="fl">0.8</span>)(l7b)</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>    l8 <span class="op">=</span>   Add()([l1b, l2b, l3b, l4b, l5b, l6b, l7b])</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>    l9 <span class="op">=</span>   Activation(<span class="st">'relu'</span>)(l8)</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>    l21 <span class="op">=</span>  Conv1D(<span class="dv">1</span>, <span class="dv">1</span>, activation<span class="op">=</span><span class="st">'linear'</span>, use_bias<span class="op">=</span><span class="va">False</span>)(l9)</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> Model(inputs<span class="op">=</span><span class="bu">input</span>, outputs<span class="op">=</span>l21)</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">compile</span>(loss<span class="op">=</span><span class="st">'mae'</span>, optimizer<span class="op">=</span>optimizers.Adam(),</span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>metrics<span class="op">=</span>[<span class="st">'mse'</span>])</span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="transformer" class="level3">
<h3 class="anchored" data-anchor-id="transformer">Transformer</h3>
<p>The transformer architecture was introduced in the paper “Attention is All You Need” by Vaswani et al.&nbsp;in 2017. It is a deep learning architecture that is based on the self-attention mechanism. The self-attention mechanism allows the network to weigh the importance of each input feature when making a prediction.</p>
<p>Transformers introduced two building blocks – multi-head attention and positional embeddings. Rather than working sequentially, sequences are processed as a whole rather than item by item. They employ self-attention, where similarity scores between items in a sentence are stored.</p>
<p>There are a lot of works that have been done to adapt the transformer architecture to time series forecasting. The main idea is to use the transformer architecture to capture the temporal dependencies in the time series. Check this blog <a href="https://huggingface.co/blog/autoformer">Yes, Transformers are Effective for Time Series Forecasting (+ Autoformer)</a> or this <a href="https://arxiv.org/pdf/2202.07125.pdf">paper Transformers in Time Series: A Survey</a></p>
</section>
<section id="deepar" class="level3">
<h3 class="anchored" data-anchor-id="deepar">DeepAR</h3>
<p><a href="https://arxiv.org/pdf/1704.04110.pdf">DeepAR</a> is a probabilistic forecasting algorithm developed by Amazon Web Services (AWS) as part of their SageMaker platform. It’s specifically considered as a model to benchmark for many time-series forecasting problems.</p>
<ul>
<li><p>DeepAR utilizes long short-term memory (LSTM) networks, to capture complex patterns and dependencies in the time series data. Instead of using LSTMs to calculate predictions directly, DeepAR leverages LSTMs to parameterize a Gaussian likelihood function. That is, to estimate the <span class="math inline">\(\theta = (\phi, \gamma)\)</span> parameters (mean and standard deviation) of the Gaussian function.</p></li>
<li><p>One of the key features of DeepAR is its ability to handle uncertainty in forecasts by generating probabilistic predictions. Instead of just providing a single point estimate for each forecast, DeepAR produces a full probability distribution over future values, allowing users to understand the range of possible outcomes and their associated probabilities. This can be particularly useful in various applications such as demand forecasting, financial forecasting, and resource planning, where understanding uncertainty is crucial for decision-making.</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="DeepAR.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Summary of the DeepAR model for training (left) and inference (right)</figcaption>
</figure>
</div>
<p><strong>How to train DeepAR?</strong></p>
<ol type="1">
<li>First, the LSTM cell takes as input the covariates <span class="math inline">\(x_{i,t}\)</span> of the current time step <span class="math inline">\(t\)</span> and the target variable <span class="math inline">\(z_{i, t-1}\)</span> of the previous time step <span class="math inline">\(t-1\)</span>. Also, the LSTM receives the hidden state <span class="math inline">\(h_{i, t-1}\)</span> from the previous time step. The LSTM cell outputs the hidden state <span class="math inline">\(h_{i, t}\)</span> for the current time step <span class="math inline">\(t\)</span>.</li>
<li>The <span class="math inline">\((\phi, \gamma)\)</span> values are indirectly computed from <span class="math inline">\(h_{i, t}\)</span> and become the parameters of the Gaussian likelihood function <span class="math inline">\(p(y_i | \theta_i) = l(z_{i, t} | \theta_{i, t})\)</span>. The model tries to answer this question: What are the best parameters <span class="math inline">\((\phi, \gamma)\)</span> that construct a gaussian distribution which outputs predictions as close as possible to the real values?</li>
<li>The current target value <span class="math inline">\(z_{i, t}\)</span> is then sampled from the Gaussian likelihood function <span class="math inline">\(p(y_i | \theta_i)\)</span>, and the process is repeated for the next time step.</li>
</ol>
<p>Since DeepAR trains (and predicts) a single data point each time, the model is called <strong>autoregressive</strong>.</p>
<p><strong>How to do inference?</strong></p>
<p>The steps for inference are pretty much the same as training steps. But one thing changes: the model does not sample the target value <span class="math inline">\(z_{i, t}\)</span> from the Gaussian likelihood function <span class="math inline">\(p(y_i | \theta_i)\)</span>. Instead, it uses the mean of the Gaussian likelihood function as the prediction for the target value <span class="math inline">\(z_{i, t}\)</span>.</p>
</section>
</section>
<section id="time-series-frameworks-and-libraries" class="level2">
<h2 class="anchored" data-anchor-id="time-series-frameworks-and-libraries">Time-series frameworks and libraries</h2>
<section id="prophet-1" class="level3">
<h3 class="anchored" data-anchor-id="prophet-1">Prophet</h3>
<p>As we described earlier in section above, Prophet is a simple but powerful tool for time-series forcasting. If you want to deep dive into Prophet, check the official <a href="https://github.com/facebook/prophet">repo</a></p>
</section>
<section id="darts" class="level3">
<h3 class="anchored" data-anchor-id="darts">Darts</h3>
<p>It contains a variety of models, from classics such as ARIMA to deep neural networks. The forecasting models can all be used in the same way, using fit() and predict() functions, similar to scikit-learn. The library also makes it easy to backtest models, combine the predictions of several models, and take external data into account. Darts supports both univariate and multivariate time series and models. The ML-based models can be trained on potentially large datasets containing multiple time series, and some of the models offer a rich support for probabilistic forecasting.</p>
<p>Check its <a href="https://github.com/unit8co/darts">repo</a></p>
</section>
<section id="neuralprophet" class="level3">
<h3 class="anchored" data-anchor-id="neuralprophet">NeuralProphet</h3>
<p>NeuralProphet is a framework for interpretable time series forecasting. NeuralProphet is built on PyTorch and combines Neural Networks and traditional time-series algorithms, inspired by Facebook Prophet and AR-Net.</p>
<p>Check the official <a href="https://github.com/ourownstory/neural_prophet">repo</a> for more details.</p>
</section>
<section id="pytorch-forecasting" class="level3">
<h3 class="anchored" data-anchor-id="pytorch-forecasting">pytorch-forecasting</h3>
<p>This <a href="https://github.com/jdb78/pytorch-forecasting">repo</a> is quite nice since it provides a training pipeline on pandas dataframes and leverages Pytorch Lightning for scalable training on multiple GPUs. It includes DeepAR, N-BEATS, and Temporal Fusion Transformers.</p>
</section>
</section>
<section id="practical-example" class="level2">
<h2 class="anchored" data-anchor-id="practical-example">Practical example</h2>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error, mean_absolute_error</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.graphics.tsaplots <span class="im">import</span> plot_acf, plot_pacf</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.seasonal <span class="im">import</span> seasonal_decompose, STL</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.diagnostic <span class="im">import</span> acorr_ljungbox</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.statespace.sarimax <span class="im">import</span> SARIMAX</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.arima_process <span class="im">import</span> ArmaProcess</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.graphics.gofplots <span class="im">import</span> qqplot</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.stattools <span class="im">import</span> adfuller</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tqdm <span class="im">import</span> tqdm</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> itertools <span class="im">import</span> product</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> typing <span class="im">import</span> Union</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="dataset-overview" class="level3">
<h3 class="anchored" data-anchor-id="dataset-overview">Dataset overview</h3>
<p>We will go back to our dataset in the first section to try out some practices.</p>
<blockquote class="blockquote">
<p>The Airline Passengers dataset describes the total number of airline passengers over a period of time. The units are a count of the number of airline passengers in thousands. There are 144 monthly observations from 1949 to 1960.</p>
</blockquote>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv'</span>, header<span class="op">=</span><span class="dv">0</span>, index_col<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Passengers</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Month</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1949-01</td>
<td>112</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1949-02</td>
<td>118</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1949-03</td>
<td>132</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1949-04</td>
<td>129</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1949-05</td>
<td>121</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="identify-and-visualize-the-seasonal-component-of-the-time-series" class="level3">
<h3 class="anchored" data-anchor-id="identify-and-visualize-the-seasonal-component-of-the-time-series">1. Identify and visualize the seasonal component of the time series</h3>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.seasonal <span class="im">import</span> STL</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>decomposition <span class="op">=</span> STL(df[<span class="st">'Passengers'</span>], period<span class="op">=</span><span class="dv">12</span>).fit()</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2, ax3, ax4) <span class="op">=</span> plt.subplots(nrows<span class="op">=</span><span class="dv">4</span>, ncols<span class="op">=</span><span class="dv">1</span>, sharex<span class="op">=</span><span class="va">True</span>, figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">8</span>))</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>ax1.plot(decomposition.observed)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'Observed'</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>ax2.plot(decomposition.trend)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">'Trend'</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>ax3.plot(decomposition.seasonal)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>ax3.set_ylabel(<span class="st">'Seasonal'</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>ax4.plot(decomposition.resid)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>ax4.set_ylabel(<span class="st">'Residuals'</span>)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>plt.xticks(np.arange(<span class="dv">0</span>, <span class="dv">145</span>, <span class="dv">12</span>), np.arange(<span class="dv">1949</span>, <span class="dv">1962</span>, <span class="dv">1</span>))</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>fig.autofmt_xdate()</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="time-series_files/figure-html/cell-11-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="apply-the-adf-test-to-check-if-the-time-series-is-stationary" class="level3">
<h3 class="anchored" data-anchor-id="apply-the-adf-test-to-check-if-the-time-series-is-stationary">2. Apply the ADF test to check if the time series is stationary</h3>
<p>The presenece of a trend means that our series is likely non-stationary. Let’s verify that using the Augmented Dickey-Fuller (ADF) test.</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.stattools <span class="im">import</span> adfuller</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>ADF_result <span class="op">=</span> adfuller(df[<span class="st">'Passengers'</span>])</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'ADF Statistic: </span><span class="sc">{</span>ADF_result[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'p-value: </span><span class="sc">{</span>ADF_result[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF Statistic: 0.8153688792060447
p-value: 0.9918802434376409</code></pre>
</div>
</div>
<p>The ADF statistic of 0.815 is not a large negative number and p-value of 0.991, which is greater than 0.05, we cannot reject the null hypothesis stating that our time series is not stationary. Therefore, our series is not stationary.</p>
</section>
<section id="apply-a-transformation-to-make-the-time-series-stationary" class="level3">
<h3 class="anchored" data-anchor-id="apply-a-transformation-to-make-the-time-series-stationary">3. Apply a transformation to make the time series stationary</h3>
<p>To remove the effect of the trend and stabilize the mean of the series, we will use differencing.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>df_diff <span class="op">=</span> np.diff(df[<span class="st">'Passengers'</span>], n<span class="op">=</span><span class="dv">1</span>) <span class="co"># n=1 for first order differencing</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>ADF_result <span class="op">=</span> adfuller(df_diff)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'ADF Statistic: </span><span class="sc">{</span>ADF_result[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'p-value: </span><span class="sc">{</span>ADF_result[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF Statistic: -2.8292668241699794
p-value: 0.054213290283828236</code></pre>
</div>
</div>
<p>This returns an ADF statistic of -2.83 and a p-value of 0.054. We can’t reject the null hypothesis, and differencing the series once did not make it stationary. We will try differencing the series again.</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>df_diff_second <span class="op">=</span> np.diff(df_diff, n<span class="op">=</span><span class="dv">1</span>) <span class="co"># n=1 for first order differencing</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>ADF_result <span class="op">=</span> adfuller(df_diff_second)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'ADF Statistic: </span><span class="sc">{</span>ADF_result[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'p-value: </span><span class="sc">{</span>ADF_result[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF Statistic: -16.38423154246855
p-value: 2.732891850013928e-29</code></pre>
</div>
</div>
<p>Now, we can reject the null hypothesis, and our series is considered to be stationary. Since the series was differenced twice to become stationary, thus d = 2</p>
</section>
<section id="fitting-arima-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-arima-model">Fitting ARIMA model</h3>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> optimize_ARIMA(endog: Union[pd.Series, <span class="bu">list</span>], order_list: <span class="bu">list</span>, d: <span class="bu">int</span>) <span class="op">-&gt;</span> pd.DataFrame:</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    results <span class="op">=</span> []</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> order <span class="kw">in</span> tqdm(order_list):</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">try</span>: </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>            model <span class="op">=</span> SARIMAX(endog, order<span class="op">=</span>(order[<span class="dv">0</span>], d, order[<span class="dv">1</span>]), simple_differencing<span class="op">=</span><span class="va">False</span>).fit(disp<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">except</span>:</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>        aic <span class="op">=</span> model.aic</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>        results.append([order, aic])</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    result_df <span class="op">=</span> pd.DataFrame(results)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    result_df.columns <span class="op">=</span> [<span class="st">'(p,q)'</span>, <span class="st">'AIC'</span>]</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Sort in ascending order, lower AIC is better</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>    result_df <span class="op">=</span> result_df.sort_values(by<span class="op">=</span><span class="st">'AIC'</span>, ascending<span class="op">=</span><span class="va">True</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> result_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>ps <span class="op">=</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">13</span>, <span class="dv">1</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>qs <span class="op">=</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">13</span>, <span class="dv">1</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>ARIMA_order_list <span class="op">=</span> <span class="bu">list</span>(product(ps, qs))</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>train <span class="op">=</span> df[<span class="st">'Passengers'</span>][:<span class="op">-</span><span class="dv">12</span>]</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>ARIMA_result_df <span class="op">=</span> optimize_ARIMA(train, ARIMA_order_list, d)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>ARIMA_result_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>  2%|▏         | 4/169 [00:00&lt;00:10, 15.99it/s]100%|██████████| 169/169 [19:08&lt;00:00,  6.79s/it]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">(p,q)</th>
<th data-quarto-table-cell-role="th">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>(11, 3)</td>
<td>1016.838772</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>(11, 4)</td>
<td>1019.018847</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>(11, 5)</td>
<td>1020.377574</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>(11, 1)</td>
<td>1021.028121</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>(12, 0)</td>
<td>1021.231718</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">164</td>
<td>(5, 0)</td>
<td>1281.732157</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">165</td>
<td>(3, 0)</td>
<td>1300.282335</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">166</td>
<td>(2, 0)</td>
<td>1302.913196</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">167</td>
<td>(1, 0)</td>
<td>1308.152194</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">168</td>
<td>(0, 0)</td>
<td>1311.919269</td>
</tr>
</tbody>
</table>

<p>169 rows × 2 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_fit.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               SARIMAX Results                                
==============================================================================
Dep. Variable:             Passengers   No. Observations:                  132
Model:                ARIMA(11, 2, 3)   Log Likelihood                -493.419
Date:                Mon, 19 Feb 2024   AIC                           1016.839
Time:                        23:33:01   BIC                           1059.852
Sample:                    01-01-1949   HQIC                          1034.316
                         - 12-01-1959                                         
Covariance Type:                  opg                                         
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1         -0.8239      0.100     -8.217      0.000      -1.020      -0.627
ar.L2         -0.9630      0.049    -19.750      0.000      -1.059      -0.867
ar.L3         -0.8520      0.087     -9.749      0.000      -1.023      -0.681
ar.L4         -0.9539      0.047    -20.370      0.000      -1.046      -0.862
ar.L5         -0.8331      0.092     -9.102      0.000      -1.013      -0.654
ar.L6         -0.9500      0.043    -22.211      0.000      -1.034      -0.866
ar.L7         -0.8361      0.089     -9.406      0.000      -1.010      -0.662
ar.L8         -0.9624      0.049    -19.607      0.000      -1.059      -0.866
ar.L9         -0.8250      0.086     -9.602      0.000      -0.993      -0.657
ar.L10        -0.9581      0.031    -30.930      0.000      -1.019      -0.897
ar.L11        -0.8087      0.096     -8.468      0.000      -0.996      -0.622
ma.L1         -0.3339      0.136     -2.456      0.014      -0.600      -0.067
ma.L2          0.2206      0.161      1.374      0.170      -0.094       0.535
ma.L3         -0.2910      0.141     -2.061      0.039      -0.568      -0.014
sigma2       104.3926     17.689      5.901      0.000      69.722     139.063
===================================================================================
Ljung-Box (L1) (Q):                   0.00   Jarque-Bera (JB):                 3.82
Prob(Q):                              0.96   Prob(JB):                         0.15
Heteroskedasticity (H):               2.23   Skew:                            -0.02
Prob(H) (two-sided):                  0.01   Kurtosis:                         3.84
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).</code></pre>
</div>
</div>
<p>The result shows that a value of p = 11 and q = 3 is the best fit for our model, which results in the lowest AIC value. Therefore, and ARIMA(11,2,3) model is the most suitable for our time series.</p>
<p>We then fit an ARIMA(11,2,3) model to our time series and plot the residuals. The residuals should be normally distributed, with a mean of 0 and a constant variance. If the residuals are not normally distributed, then the model is not capturing all the information in the data. If the residuals have a mean different from 0, then the model is biased. If the variance of the residuals is not constant, then the model is not capturing all the information in the data.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.arima.model <span class="im">import</span> ARIMA </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> ARIMA(train, order<span class="op">=</span>(<span class="dv">11</span>, <span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>model_fit <span class="op">=</span> model.fit()</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>_ <span class="op">=</span> model_fit.plot_diagnostics(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">8</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="time-series_files/figure-html/cell-18-output-1.png" class="img-fluid"></p>
</div>
</div>
<ul>
<li>The top-left plot shows the residuals over time. While there is no trend in the residuals, the variance does not seem to be constant, which is a discrepancy in comparison to white noise</li>
<li>The top-right plot shows the distribution of the residuals, which is close to a normal distribution.</li>
<li>The bottom-left plot (Q-Q plot) displays a line that is fairly straight, indicating that the residuals are normally distributed.</li>
<li>The bottom-right plot shows the autocorrelation of the residuals, which is close to 0 for all lags, indicating that the residuals are uncorrelated.</li>
</ul>
<p>Therefore, from a qualitative standpoint, it seems that our residuals are close to white noise, which is a good sign, as it means that the model’s errors are random.</p>
<p>Our model then can be used to forecast future values of the time series.</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>test <span class="op">=</span> df.iloc[<span class="op">-</span><span class="dv">12</span>:]</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>test[<span class="st">'naive_seasonal'</span>] <span class="op">=</span> df[<span class="st">'Passengers'</span>].iloc[<span class="dv">120</span>:<span class="dv">132</span>].values</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>ARIMA_pred <span class="op">=</span> model_fit.get_prediction(<span class="dv">132</span>, <span class="dv">143</span>).predicted_mean</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>test[<span class="st">'ARIMA_pred'</span>] <span class="op">=</span> ARIMA_pred.values</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Passengers</th>
<th data-quarto-table-cell-role="th">naive_seasonal</th>
<th data-quarto-table-cell-role="th">ARIMA_pred</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Month</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1960-01</td>
<td>417</td>
<td>360</td>
<td>422.368712</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1960-02</td>
<td>391</td>
<td>342</td>
<td>410.637667</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1960-03</td>
<td>419</td>
<td>406</td>
<td>461.827488</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1960-04</td>
<td>461</td>
<td>396</td>
<td>457.827939</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1960-05</td>
<td>472</td>
<td>420</td>
<td>481.698510</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1960-06</td>
<td>535</td>
<td>472</td>
<td>531.108649</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1960-07</td>
<td>622</td>
<td>548</td>
<td>606.151268</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1960-08</td>
<td>606</td>
<td>559</td>
<td>615.479569</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1960-09</td>
<td>508</td>
<td>463</td>
<td>525.628309</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1960-10</td>
<td>461</td>
<td>407</td>
<td>467.123847</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1960-11</td>
<td>390</td>
<td>362</td>
<td>425.079157</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1960-12</td>
<td>432</td>
<td>405</td>
<td>467.360271</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>ax.plot(df.index, df[<span class="st">'Passengers'</span>])</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>ax.plot(test[<span class="st">'Passengers'</span>], <span class="st">'b-'</span>, label<span class="op">=</span><span class="st">'actual'</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>ax.plot(test[<span class="st">'naive_seasonal'</span>], <span class="st">'r:'</span>, label<span class="op">=</span><span class="st">'naive seasonal'</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>ax.plot(test[<span class="st">'ARIMA_pred'</span>], <span class="st">'k--'</span>, label<span class="op">=</span><span class="st">'ARIMA(11,2,3)'</span>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Date'</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Number of air passengers'</span>)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>ax.axvspan(<span class="dv">132</span>, <span class="dv">143</span>, color<span class="op">=</span><span class="st">'#808080'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>plt.xticks(np.arange(<span class="dv">0</span>, <span class="dv">145</span>, <span class="dv">12</span>), np.arange(<span class="dv">1949</span>, <span class="dv">1962</span>, <span class="dv">1</span>))</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="dv">120</span>, <span class="dv">143</span>)</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>fig.autofmt_xdate()</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="time-series_files/figure-html/cell-20-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="fitting-sarima-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-sarima-model">Fitting SARIMA model</h3>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> optimize_SARIMA(endog: Union[pd.Series, <span class="bu">list</span>], order_list: <span class="bu">list</span>, d: <span class="bu">int</span>, D: <span class="bu">int</span>, s: <span class="bu">int</span>) <span class="op">-&gt;</span> pd.DataFrame:</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    results <span class="op">=</span> []</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> order <span class="kw">in</span> tqdm(order_list):</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">try</span>: </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>            model <span class="op">=</span> SARIMAX(</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>                endog, </span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>                order<span class="op">=</span>(order[<span class="dv">0</span>], d, order[<span class="dv">1</span>]),</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>                seasonal_order<span class="op">=</span>(order[<span class="dv">2</span>], D, order[<span class="dv">3</span>], s),</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>                simple_differencing<span class="op">=</span><span class="va">False</span>).fit(disp<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">except</span>:</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>        aic <span class="op">=</span> model.aic</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>        results.append([order, aic])</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>    result_df <span class="op">=</span> pd.DataFrame(results)</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>    result_df.columns <span class="op">=</span> [<span class="st">'(p,q,P,Q)'</span>, <span class="st">'AIC'</span>]</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>    <span class="co">#Sort in ascending order, lower AIC is better</span></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>    result_df <span class="op">=</span> result_df.sort_values(by<span class="op">=</span><span class="st">'AIC'</span>, ascending<span class="op">=</span><span class="va">True</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> result_df</span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>ps <span class="op">=</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">4</span>, <span class="dv">1</span>)</span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>qs <span class="op">=</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">4</span>, <span class="dv">1</span>)</span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a>Ps <span class="op">=</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">4</span>, <span class="dv">1</span>)</span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a>Qs <span class="op">=</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">4</span>, <span class="dv">1</span>)</span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a>SARIMA_order_list <span class="op">=</span> <span class="bu">list</span>(product(ps, qs, Ps, Qs))</span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a>train <span class="op">=</span> df[<span class="st">'Passengers'</span>][:<span class="op">-</span><span class="dv">12</span>]</span>
<span id="cb31-34"><a href="#cb31-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-35"><a href="#cb31-35" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb31-36"><a href="#cb31-36" aria-hidden="true" tabindex="-1"></a>D <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb31-37"><a href="#cb31-37" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> <span class="dv">12</span></span>
<span id="cb31-38"><a href="#cb31-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-39"><a href="#cb31-39" aria-hidden="true" tabindex="-1"></a>SARIMA_result_df <span class="op">=</span> optimize_SARIMA(train, SARIMA_order_list, d, D, s)</span>
<span id="cb31-40"><a href="#cb31-40" aria-hidden="true" tabindex="-1"></a>SARIMA_result_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>100%|██████████| 256/256 [1:06:31&lt;00:00, 15.59s/it]</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">(p,q,P,Q)</th>
<th data-quarto-table-cell-role="th">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>(2, 1, 1, 2)</td>
<td>892.232482</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>(2, 1, 2, 1)</td>
<td>893.527182</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>(2, 1, 1, 3)</td>
<td>894.093579</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>(1, 0, 1, 2)</td>
<td>894.287516</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>(0, 1, 1, 2)</td>
<td>894.987878</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">250</td>
<td>(0, 0, 2, 0)</td>
<td>906.940147</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">251</td>
<td>(3, 2, 0, 3)</td>
<td>907.181875</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">252</td>
<td>(0, 0, 3, 2)</td>
<td>907.514319</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">253</td>
<td>(0, 0, 3, 0)</td>
<td>908.742583</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">254</td>
<td>(0, 0, 0, 3)</td>
<td>908.781405</td>
</tr>
</tbody>
</table>

<p>255 rows × 2 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>SARIMA_model <span class="op">=</span> SARIMAX(train, order<span class="op">=</span>(<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">1</span>), seasonal_order<span class="op">=</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">12</span>), simple_differencing<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>SARIMA_model_fit <span class="op">=</span> SARIMA_model.fit(disp<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(SARIMA_model_fit.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                        SARIMAX Results                                        
===============================================================================================
Dep. Variable:                              Passengers   No. Observations:                  132
Model:             SARIMAX(2, 1, 1)x(1, 1, [1, 2], 12)   Log Likelihood                -439.116
Date:                                 Tue, 20 Feb 2024   AIC                            892.232
Time:                                         10:19:10   BIC                            911.686
Sample:                                     01-01-1949   HQIC                           900.132
                                          - 12-01-1959                                         
Covariance Type:                                   opg                                         
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
ar.L1         -1.2665      0.085    -14.945      0.000      -1.433      -1.100
ar.L2         -0.3404      0.077     -4.401      0.000      -0.492      -0.189
ma.L1          0.9997      0.666      1.502      0.133      -0.305       2.305
ar.S.L12       0.9993      0.111      9.043      0.000       0.783       1.216
ma.S.L12      -1.3391      2.067     -0.648      0.517      -5.390       2.712
ma.S.L24       0.3581      0.655      0.546      0.585      -0.926       1.642
sigma2        78.2020    148.583      0.526      0.599    -213.015     369.419
===================================================================================
Ljung-Box (L1) (Q):                   0.06   Jarque-Bera (JB):                 0.90
Prob(Q):                              0.80   Prob(JB):                         0.64
Heteroskedasticity (H):               1.56   Skew:                            -0.08
Prob(H) (two-sided):                  0.16   Kurtosis:                         3.39
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).</code></pre>
</div>
</div>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>SARIMA_model_fit.plot_diagnostics(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">8</span>))<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="time-series_files/figure-html/cell-23-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The final test to determine whether we can use this model for forecasting or not is the Ljung-Box test.</p>
<div class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.diagnostic <span class="im">import</span> acorr_ljungbox</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>residuals <span class="op">=</span> SARIMA_model_fit.resid</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>df_stats <span class="op">=</span> acorr_ljungbox(residuals.values, lags<span class="op">=</span> np.arange(<span class="dv">1</span>, <span class="dv">11</span>, <span class="dv">1</span>))</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>df_stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="43">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">lb_stat</th>
<th data-quarto-table-cell-role="th">lb_pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>0.004873</td>
<td>0.944347</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>0.745767</td>
<td>0.688746</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>1.022897</td>
<td>0.795712</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>1.227105</td>
<td>0.873616</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>1.436496</td>
<td>0.920280</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6</td>
<td>1.712124</td>
<td>0.944181</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7</td>
<td>2.308987</td>
<td>0.940781</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8</td>
<td>2.719618</td>
<td>0.950703</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">9</td>
<td>2.736189</td>
<td>0.973843</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">10</td>
<td>4.969893</td>
<td>0.893180</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The returned p-values are all greater than 0.05. Therefore, we do not reject the null hypothesis, and we conclude that the residuals are independent and uncorrelated, just like white noise. Our model has passed all the tests from the residuals analysis, and we are ready to use it for forecasting.</p>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>SARIMA_pred <span class="op">=</span> SARIMA_model_fit.get_prediction(<span class="dv">132</span>, <span class="dv">143</span>).predicted_mean</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>test[<span class="st">'SARIMA_pred'</span>] <span class="op">=</span> SARIMA_pred.values</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="49">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Passengers</th>
<th data-quarto-table-cell-role="th">naive_seasonal</th>
<th data-quarto-table-cell-role="th">ARIMA_pred</th>
<th data-quarto-table-cell-role="th">SARIMA_pred</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Month</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1960-01</td>
<td>417</td>
<td>360</td>
<td>422.368712</td>
<td>418.513901</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1960-02</td>
<td>391</td>
<td>342</td>
<td>410.637667</td>
<td>399.577187</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1960-03</td>
<td>419</td>
<td>406</td>
<td>461.827488</td>
<td>461.313429</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1960-04</td>
<td>461</td>
<td>396</td>
<td>457.827939</td>
<td>451.452634</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1960-05</td>
<td>472</td>
<td>420</td>
<td>481.698510</td>
<td>473.744198</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1960-06</td>
<td>535</td>
<td>472</td>
<td>531.108649</td>
<td>538.788480</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1960-07</td>
<td>622</td>
<td>548</td>
<td>606.151268</td>
<td>612.440323</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1960-08</td>
<td>606</td>
<td>559</td>
<td>615.479569</td>
<td>624.594874</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1960-09</td>
<td>508</td>
<td>463</td>
<td>525.628309</td>
<td>520.173138</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1960-10</td>
<td>461</td>
<td>407</td>
<td>467.123847</td>
<td>462.852995</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1960-11</td>
<td>390</td>
<td>362</td>
<td>425.079157</td>
<td>412.723148</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1960-12</td>
<td>432</td>
<td>405</td>
<td>467.360271</td>
<td>454.252799</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>ax.plot(df.index, df[<span class="st">'Passengers'</span>])</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>ax.plot(test[<span class="st">'Passengers'</span>], <span class="st">'b-'</span>, label<span class="op">=</span><span class="st">'actual'</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>ax.plot(test[<span class="st">'naive_seasonal'</span>], <span class="st">'r:'</span>, label<span class="op">=</span><span class="st">'naive seasonal'</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>ax.plot(test[<span class="st">'ARIMA_pred'</span>], <span class="st">'k--'</span>, label<span class="op">=</span><span class="st">'ARIMA(11,2,3)'</span>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>ax.plot(test[<span class="st">'SARIMA_pred'</span>], <span class="st">'g-.'</span>, label<span class="op">=</span><span class="st">'SARIMA(2,1,1)(1,1,2,12)'</span>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Date'</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Number of air passengers'</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>ax.axvspan(<span class="dv">132</span>, <span class="dv">143</span>, color<span class="op">=</span><span class="st">'#808080'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>plt.xticks(np.arange(<span class="dv">0</span>, <span class="dv">145</span>, <span class="dv">12</span>), np.arange(<span class="dv">1949</span>, <span class="dv">1962</span>, <span class="dv">1</span>))</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="dv">120</span>, <span class="dv">143</span>)</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>fig.autofmt_xdate()</span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="time-series_files/figure-html/cell-26-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>We’ll use the mean absolute percentage error (MAPE) to evaluate each model.</p>
<div class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mape(y_true, y_pred):</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.mean(np.<span class="bu">abs</span>((y_true <span class="op">-</span> y_pred) <span class="op">/</span> y_true)) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>mape_naive_seasonal <span class="op">=</span> mape(test[<span class="st">'Passengers'</span>], test[<span class="st">'naive_seasonal'</span>])</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>mape_ARIMA <span class="op">=</span> mape(test[<span class="st">'Passengers'</span>], test[<span class="st">'ARIMA_pred'</span>])</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>mape_SARIMA <span class="op">=</span> mape(test[<span class="st">'Passengers'</span>], test[<span class="st">'SARIMA_pred'</span>])</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'MAPE Naive Seasonal: </span><span class="sc">{</span>mape_naive_seasonal<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'MAPE ARIMA: </span><span class="sc">{</span>mape_ARIMA<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'MAPE SARIMA: </span><span class="sc">{</span>mape_SARIMA<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>MAPE Naive Seasonal: 9.987532920823485
MAPE ARIMA: 3.8410155255655063
MAPE SARIMA: 2.8487689091201363</code></pre>
</div>
</div>
<div class="cell" data-execution_count="55">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> [<span class="st">'naive seasonal'</span>, <span class="st">'ARIMA(11,2,3)'</span>, <span class="st">'SARIMA(2,1,1)(1,1,2,12)'</span>]</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> [mape_naive_seasonal, mape_ARIMA, mape_SARIMA]</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>ax.bar(x, y, width<span class="op">=</span><span class="fl">0.4</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Models'</span>)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'MAPE (%)'</span>)</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="dv">15</span>)</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, value <span class="kw">in</span> <span class="bu">enumerate</span>(y):</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>    plt.text(x<span class="op">=</span>index, y<span class="op">=</span>value <span class="op">+</span> <span class="dv">1</span>, s<span class="op">=</span><span class="bu">str</span>(<span class="bu">round</span>(value,<span class="dv">2</span>)), ha<span class="op">=</span><span class="st">'center'</span>)</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="time-series_files/figure-html/cell-28-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>So the SARIMA model is the better performing method for this situation compared to our naive and ARIMA models. This makes sense, since our dataset had clear seasonality, and the SARIMA model is built to use the seasonal properties of time series to make forecasts.</p>
</section>
<section id="prophet-2" class="level3">
<h3 class="anchored" data-anchor-id="prophet-2">Prophet</h3>
<p>Prophet follows the sklearn API, where a model is initialized by creating an instance of the Prophet class, the model is trained using the fit method, and predictions are generated using the predict method. Therefore, we’ll first initialize a Prophet model by creating an instance of the Prophet class</p>
<div class="cell" data-execution_count="62">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> prophet <span class="im">import</span> Prophet</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> Prophet()</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>train <span class="op">=</span> train.reset_index().rename(columns<span class="op">=</span>{<span class="st">'Month'</span>:<span class="st">'ds'</span>, <span class="st">'Passengers'</span>:<span class="st">'y'</span>})</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>test <span class="op">=</span> test.reset_index().rename(columns<span class="op">=</span>{<span class="st">'Month'</span>:<span class="st">'ds'</span>, <span class="st">'Passengers'</span>:<span class="st">'y'</span>})</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>model.fit(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>14:07:39 - cmdstanpy - INFO - Chain [1] start processing
14:07:41 - cmdstanpy - INFO - Chain [1] done processing</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="62">
<pre><code>&lt;prophet.forecaster.Prophet at 0x2a3f1b810&gt;</code></pre>
</div>
</div>
<div class="cell" data-execution_count="63">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>prophet_pred <span class="op">=</span> model.predict(test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="83">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MAPE prophet: </span><span class="sc">{</span>mape(test[<span class="st">'y'</span>], prophet_pred[<span class="st">'yhat'</span>])<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>MAPE prophet: 6.615923942230125</code></pre>
</div>
</div>
<p>Prophet comes with many methods that allow us to quickly visualize a model’s predic- tions or its different components.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>_ <span class="op">=</span> model.plot(prophet_pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="time-series_files/figure-html/cell-32-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>We can also display the different components used in our model</p>
<div class="cell" data-execution_count="77">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>fig2 <span class="op">=</span> model.plot_components(prophet_pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="time-series_files/figure-html/cell-33-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li><a href="https://www.manning.com/books/time-series-forecasting-in-python-book">Time Series Forecasting in Python</a> by Marco Peixeiro</li>
<li>Machine Learning for Time Series with Python By Ben Auffarth</li>
<li>Darts</li>
</ol>
<p>If you liked this article, please follow me on <a href="https://medium.com/@jonathan.tunguyen">Medium</a> and Twitter <a href="https://twitter.com/jonathan_ttu"><span class="citation" data-cites="jonathan_ttu">@jonathan_ttu</span></a>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="https://github.com/mrtunguyen/mrtunguyen.github.io" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->



</body></html>